stackExchangeQuestion:
  issues:
    # Post a comment, `{issue-author}` is an optional placeholder
    comment: >
      :wave: @{issue-author}, please use our [stack exchange](https://solana.stackexchange.com/questions) to help answer your question!
    # Close the issue
    close: true
